
OBJECTS = $(SOURCES_DIR)/search.o \
		  $(SOURCES_DIR)/term.o \
		  $(SOURCES_DIR)/data_handler.o \
		  $(SOURCES_DIR)/pages_connection.o \
		  $(SOURCES_DIR)/url_data.o \
		  $(SOURCES_DIR)/query.o

-include ../makefile.common
