
OBJECTS = $(SOURCES_DIR)/search.o \
		  $(SOURCES_DIR)/ui.o \
		  $(SOURCES_DIR)/data_handler.o \
		  $(SOURCES_DIR)/term.o \
		  $(SOURCES_DIR)/manager.o \
		  $(SOURCES_DIR)/pages_connection.o \
		  $(SOURCES_DIR)/url_data.o \
		  $(SOURCES_DIR)/crawler.o \
		  $(SOURCES_DIR)/url_data_download.o \
		  $(SOURCES_DIR)/page_data_analyzer.o \
		  $(SOURCES_DIR)/page.o \
		  $(SOURCES_DIR)/config_info.o \
		  $(SOURCES_DIR)/config_json.o \
		  $(SOURCES_DIR)/validator.o \
		  $(SOURCES_DIR)/query.o

-include ../makefile.common
